import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Repository = {
  id: number;
  stargazers_count: number;
  name: string;
  full_name: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const res = await fetch('https://api.github.com/repos/vercel/next.js');
  const data: Repository = await res.json();

  return (
    <html lang="en">
      <body>
        <Link href="/" >
          <h1>{data.full_name}</h1>
        </Link>
        {children}
      </body>
    </html>
  )
}
